name: Build Magisk Module ZIP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get install zip

      - name: Create ZIP file
        run: zip -r magisk-module.zip *

      - name: Upload ZIP to Release
        uses: softprops/action-gh-release@v1
        with:
          files: magisk-module.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
